version: "3"
services:
  api: 
    image: docker_username/repo_name # change this
    depends_on:
      - postgres
    ports: 
      - 80:8000
    # env_file:
    #   - ./.env
    environment:
      - DB_HOST=${DB_HOST} # postgres service from line 18
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORT=${DB_PASSWORT}
      - DB_USERNAME=${DB_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: