name: Build and Deploy Code

on:
  push:
    branches:
      - "master"

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi
        run: echo "Hi Test"
